steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
  
  # Build the application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
  
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/teacher-job-portal:$COMMIT_SHA', '.']
  
  # Push container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/teacher-job-portal:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'teacher-job-portal'
      - '--image'
      - 'gcr.io/$PROJECT_ID/teacher-job-portal:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'

images:
  - 'gcr.io/$PROJECT_ID/teacher-job-portal:$COMMIT_SHA'